**Part A**

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [3]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 4], [7, 8]])

vertical_stack = np.vstack((A, B))

horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 4]
 [7 8]]
Horizontal Stack:
 [[1 2 5 4]
 [3 4 7 8]]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [4]:
common_elements = np.intersect1d(A, B)
print("Common elements between A and B:", common_elements)

Common elements between A and B: [4]


3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [5]:
lower_bound = 2
upper_bound = 4

elements_in_range = A[(A >= lower_bound) & (A <= upper_bound)]
print(f"Elements in A between {lower_bound} and {upper_bound}:", elements_in_range)

Elements in A between 2 and 4: [2 3 4]


4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered rows:\n", filtered_rows)

Filtered rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


**Part B**

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [9]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.iloc[::20, [0, 1, 2]]

display(filtered_df)

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [10]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

from IPython.display import display
display(df[['Min.Price', 'Max.Price']])

Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

In [ ]:
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

filtered_rows = df[df.sum(axis=1) > 100]

tools.display_dataframe_to_user(name="Rows with Sum > 100", dataframe=filtered_rows)